version: 2.1

jobs:
  init:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: NPM Install
          command: npm i
      - run:
          name: Install ci tools
          command: 'mkdir -p ~/.build_tools/node && npm install --prefix ~/.build_tools/node kl-ci-tools'
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
            - ~/.build_tools
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: NPM Build
          command: npm run build
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
            - ~/.build_tools
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  publish-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Set Develop Version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js tag dev.[]
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag develop
  publish-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Verify dep versions
          command: ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js validate
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag latest

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - init
      - build:
          requires:
            - init
      - test:
          requires:
            - build
      - publish-dev:
          requires:
            - test
          filters:
            branches:
              only: develop
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: develop
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/
