version: 2

jobs:
  init-deps:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: NPM Install
          command: npm i
      - run:
          name: Install ci tools
          command: 'sudo npm i -g kl-ci-tools'
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: NPM Build
          command: npm run build
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  publish-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Set Develop Version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] kl-ci-tools tag dev.[]
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag develop
  publish-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Verify dep versions
          command: kl-ci-tools validate

workflows:
  version: 2
  build_and_test:
    jobs:
      - init-deps
      - build:
          requires:
            - init-deps
      - test:
          requires:
            - init-deps
            - build
      - publish-dev:
          requires:
            - init-deps
            - build
            - test
          filters:
            branches:
              only: develop
      - pubish-version:
          requires:
            - init-deps
            - build
            - test
          filters:
            branches:
              only: develop
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
