version: 2.1

jobs:
  init:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: NPM Install
          command: npm i
      - run:
          name: Install ci tools
          command: 'mkdir -p ~/.build_tools/node && npm install --prefix ~/.build_tools/node kl-ci-tools'
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
            - ~/.build_tools
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: NPM Build
          command: npm run build
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
            - ~/.build_tools
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  publish-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Set Develop Version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js tag dev.[]
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag develop
  publish-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Verify dep versions
          command: ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js validate
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag latest
  trigger-release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install ci tools
          command: 'sudo npm install -g kl-ci-tools'
      - run:
          name: checkout release branch
          command: git checkout -b release/$CIRCLE_TAG
      - run:
          name: create git user
          command: git config user.email "dev@mazzaroth.io" && git config user.name "CricleCI"
      - run:
          name: update dependencies
          command: kl-ci-tools deps | xargs -I[] npm install []@latest
      - run:
          name: validate package json
          command: kl-ci-tools validate
      - run:
          name: commit updates
          command: git add -A && git commit -m "Dependency update for release $CIRCLE_TAG"
      - run:
          name: push release branch
          command: git push origin release/$CIRCLE_TAG


workflows:
  version: 2.1
  start_release:
    jobs:
      - trigger-release:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/
            branches:
              ignore: /.*/
  build_and_test:
    jobs:
      - init
      - build:
          requires:
            - init
      - test:
          requires:
            - build
      - publish-dev:
          requires:
            - test
          filters:
            branches:
              only: develop
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: /release\/v*/
