version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm i
      - run:
          name: Install ci tools
          command: 'mkdir -p ~/.build_tools/node && npm install --prefix ~/.build_tools/node kl-ci-tools'
      - run: |
          if [[ "$CIRCLE_BRANCH" =~ release/v.* ]]; then
            ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js deps | xargs -I[] npm install []@latest
          fi
      - run:
          name: debug
          command: cat package.json
      - save_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
          paths:
            - package.json
            - node_modules
            - ~/.build_tools
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: debug
          command: cat package.json
      - run:
          name: NPM Build
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
          paths:
            - package.json
            - dist
            - node_modules
            - ~/.build_tools


  publish-dev:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: Set Develop Version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js tag dev.[]
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag develop

  publish-latest:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: create git user
          command: git config user.email "dev@mazzaroth.io" && git config user.name "CricleCI"
      - run:
          name: update version
          command: echo $CIRCLE_BRANCH | sed 's:release/::' | xargs npm version --force
      - run:
          name: Verify package.json
          command: ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js validate
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: commit updates
          command: git add -A && git commit -m "Dependency update for $CIRCLE_BRANCH"
      - run:
          name: Merge back to master
          command: git checkout master && git merge $CIRCLE_BRANCH
      - run:
          name: Publish package
          command: npm publish --tag latest

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - init
      - test:
          requires:
            - init
      - publish-dev:
          requires:
            - test
          filters:
            branches:
              only: develop
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: /release\/v([0-9]+)\.([0-9]+)\.([0-9]+)$/
